-- IDENTIFY APPLICATION SCHEMA
SELECT SCHEMA_NAME FROM "HCP"."HCP_DEV_METADATA";

-- IDENTIFY CURRENT USER
SELECT CURRENT_USER FROM DUMMY;

-- VERIFY PREDICTIVE ANALYSIS LIBRARY IS AVAILABLE
SELECT * FROM SYS.AFL_FUNCTIONS WHERE PACKAGE_NAME='PAL';

-- SET APPLICATION SCHEMA - PASTE IN VALUE BELOW
SET SCHEMA NEO_;
