-- DO GLOBAL REPLACE ON NEO_ FIRST FOR SCHEMA

-- ENSURE CORRECT SCHEMA IS SET

-- CLEANUP
DROP TYPE PAL_T_DATA;
DROP TYPE PAL_T_PARAMS;
DROP TYPE PAL_T_RESULTS;
DROP TYPE PAL_T_CENTERS;
DROP TABLE PAL_SIGNATURE;
CALL HCP.HCP_AFL_WRAPPER_ERASER ('TWEETERS_CLUSTER');
DROP TABLE PAL_PARAMS;
DROP TABLE PAL_RESULTS;
DROP TABLE PAL_CENTERS;
DROP VIEW "TweetersClustered";
DROP VIEW "Clusters";

-- CREATE STORED PROCEDURE
CREATE TYPE PAL_T_DATA AS TABLE ("user" VARCHAR(256), "stance" INTEGER, "influence" DOUBLE);
CREATE TYPE PAL_T_PARAMS AS TABLE (NAME VARCHAR(50), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR(100));
CREATE TYPE PAL_T_RESULTS AS TABLE ("user" VARCHAR(256), "clusterNumber" INTEGER, "distance" DOUBLE);
CREATE TYPE PAL_T_CENTERS AS TABLE ("clusterNumber" INTEGER, "stance" INTEGER, "influence" INTEGER);
CREATE COLUMN TABLE PAL_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SIGNATURE VALUES (1, 'NEO_.PAL_T_DATA', 'in');
INSERT INTO PAL_SIGNATURE VALUES (2, 'NEO_.PAL_T_PARAMS', 'in');
INSERT INTO PAL_SIGNATURE VALUES (3, 'NEO_.PAL_T_RESULTS', 'out');
INSERT INTO PAL_SIGNATURE VALUES (4, 'NEO_.PAL_T_CENTERS', 'out');
CALL HCP.HCP_AFL_WRAPPER_GENERATOR ('TWEETERS_CLUSTER', 'AFLPAL', 'KMEANS', PAL_SIGNATURE);

-- CREATE PARAMETER TABLE
CREATE COLUMN TABLE PAL_PARAMS LIKE PAL_T_PARAMS;
INSERT INTO PAL_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO PAL_PARAMS VALUES ('GROUP_NUMBER', 3, null, null);
INSERT INTO PAL_PARAMS VALUES ('GROUP_NUMBER_MIN', 5, null, null);
INSERT INTO PAL_PARAMS VALUES ('GROUP_NUMBER_MAX', 10, null, null);
INSERT INTO PAL_PARAMS VALUES ('INIT_TYPE', 4, null, null);
INSERT INTO PAL_PARAMS VALUES ('DISTANCE_LEVEL', 2, null, null);
INSERT INTO PAL_PARAMS VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO PAL_PARAMS VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO PAL_PARAMS VALUES ('NORMALIZATION', 0, null, null);

-- CREATE OUTPUT TABLES
CREATE COLUMN TABLE PAL_RESULTS LIKE PAL_T_RESULTS;
CREATE COLUMN TABLE PAL_CENTERS LIKE PAL_T_CENTERS;

-- CREATE VIEWS FOR ODATA
CREATE VIEW "TweetersClustered" AS
	SELECT s.*, t."tweetCount", c."clusterNumber" + 1 AS "clusterNumber"
	 FROM "Tweeters" s
	 INNER JOIN (
		SELECT "user", COUNT(*) AS "tweetCount" 
		 FROM "Tweets"
		 GROUP BY "user"
	 	) t ON t."user" = s."user"
	 INNER JOIN "PAL_RESULTS" c ON c."user" = s."user"
	 ;
CREATE VIEW "Clusters" AS
	SELECT c."clusterNumber" + 1 AS "clusterNumber", c."stance", c."influence", t."users"
	 FROM "PAL_CENTERS" c
	 INNER JOIN (
	 	 SELECT "clusterNumber", COUNT(*) as "users"
	 	  FROM "PAL_RESULTS"  
	 	  GROUP BY "clusterNumber"
		 ) t ON t."clusterNumber" = c."clusterNumber"
	 ;

-- RUNTIME
TRUNCATE TABLE PAL_RESULTS;
TRUNCATE TABLE PAL_CENTERS;
CALL _SYS_AFL."NEO__TWEETERS_CLUSTER"("Tweeters", PAL_PARAMS, PAL_RESULTS, PAL_CENTERS) with overview;

-- REVIEW
SELECT * FROM "Tweets";
SELECT * FROM "$TA_tweets";
SELECT * FROM PAL_RESULTS;
SELECT * FROM PAL_CENTERS;
SELECT * FROM "TweetersClustered";
SELECT * FROM "Clusters";
