-- DO GLOBAL REPLACE ON p000 FIRST

CALL HCP.HCP_GRANT_ROLE_TO_USER('p000trial.dev.live3::user','p000');

-- USEFUL TO SOLVE ISSUES SHOULD ROLE OR DEPENDENCIES BE MODIFIED
CALL HCP.HCP_SYNCHRONIZE_ROLES;
